--Script para criar tabelas da aplicação
create table SISVENDA.CLIENTE
(
NOME VARCHAR2(30),
CODCLIENTE   NUMBER,
ENDERECO   VARCHAR2(100),
SALARIO   NUMBER,
CPF  NUMBER,
NRCCREDITO NUMBER
);
create table SISVENDA.PRODUTO
(
ID NUMBER,
DESCRICAO   VARCHAR2(100),
REFERENCIA   NUMBER
);
create table SISVENDA.TRANSACAOONLINE
(
ID NUMBER,
CODCLIENTE   NUMBER,
PRODUTO   VARCHAR2(100),
TIPOVENDA    VARCHAR2(100),
NRCCREDITO NUMBER
);
create table SISVENDA.TRANSACAECOMMERCE
(
ID NUMBER,
CODCLIENTE   NUMBER,
PRODUTO   VARCHAR2(100),
TIPOVENDA    VARCHAR2(100),
NRCCREDITO NUMBER
);
create table SISVENDA.FORNECEDOR
(
ID NUMBER,
CODFORN   NUMBER,
NOME   VARCHAR2(100)
);